### ISSUE TITLE
Got an error when comping gnatcov.

### ISSUE THREAD

**Issue by Fazio** [AdaCore/gnatcoverage#9]
I got this error when compling gnatcov, Can you help me to resovle it?
instrument-find_units.adb:49:23: no selector "P_Syntactic_Fully_Qualified_Name" for private type "Body_Stub" defined at libadalang-analysis.ads:421

**Comment by pmderodat** [comment]
Hello,

The problem is very likely that you are trying to build the `master` branch of `gnatcoverage` using an old Libadalang build (for instance the one from a past GNAT Community release). You should build and install Libadalang’s `stable` branch first. We just updated our build procedure to make this explicit (https://github.com/AdaCore/gnatcoverage/blob/master/tools/gnatcov/README.md#build-from-sources---quick-example-for-an-intel-linux-host). Please let us know if you still have build issues with a recent version of Libadalang.
